version: '3.8'
services:
  db:
    image: postgres:14
    environment:
      POSTGRES_DB: app
      POSTGRES_USER: app
      POSTGRES_PASSWORD: secret
    volumes:
      - db-data:/var/lib/postgresql/data
      - ./backup:/backup
      - ./server/schema.sql:/docker-entrypoint-initdb.d/schema.sql:ro
      - ./docker/db-entrypoint.sh:/usr/local/bin/db-entrypoint.sh:ro
    entrypoint: ["/usr/local/bin/db-entrypoint.sh"]
    restart: always
  server:
    build: ./server
    environment:
      DATABASE_URL: postgres://app:secret@db:5432/app
    ports:
      - "3000:3000"
    depends_on:
      - db
volumes:
  db-data:
