import db from './db';
import { QueryResult } from 'pg';

export interface User {
  id: number;
  name: string;
  // Add other user properties here based on your schema
  // email?: string;
  // password_hash?: string; // Or however you store passwords
  // created_at?: Date;
  // updated_at?: Date;
}

interface GetAllUsersOptions {
  limit?: number;
  offset?: number;
}

export async function getAll({ limit = 10, offset = 0 }: GetAllUsersOptions = {}): Promise<User[]> {
  const { rows }: QueryResult<User> = await db.query(
    'SELECT * FROM users ORDER BY id LIMIT $1 OFFSET $2',
    [limit, offset]
  );
  return rows;
}

// For create, we might not have an ID yet if it's auto-generated by the DB
// The input type could be Omit<User, 'id'> or a specific DTO interface
export interface UserCreationData {
  name: string;
  // other fields required for creation
}

export async function create(user: UserCreationData): Promise<User> {
  const { name } = user;
  const { rows }: QueryResult<User> = await db.query(
    'INSERT INTO users(name) VALUES($1) RETURNING *',
    [name]
  );
  return rows[0];
}

// Exporting functions directly
// If you prefer a default export with an object:
// export default { getAll, create };
