name: CI

on:
  pull_request:

jobs:
  docker-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Build Docker image
        run: docker build -t server-test ./server
      - name: Run tests in container
        run: docker run --rm server-test npm test
